### ISSUE TITLE
VS studio version problem

### ISSUE THREAD

**Issue by Aliceljm1** [pmateusz/TightVNC#1]
I have a question,the "tightvnc2010.sln" file in my pc can not open with vs2010,it just open with vs2012, Is this a spelling mistake?

**Comment by pmateusz** [comment]
Thank you for reporting the problem. "tightvnc2010.sln" was in fact VS 2013 solution. It was converted from original source when I was setting up the project. I renamed the file to "tightvnc2013.sln".

Original 2010 solution can be downloaded [here](http://www.tightvnc.com/download.php).
